sudo: required
services:
- docker
- docker-compose

branches:
  only:
  - prod
  - preprod

before_script:
- cd deploy
- echo $TRAVIS_COMMIT
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
- echo $TRAVIS_BUILD

script:
  if [ -z $TRAVIS_TAG ]; then TRAVIS_TAG=dev; fi && docker build --build-arg tag=${TRAVIS_TAG} -t 866680356172.dkr.ecr.us-east-2.amazonaws.com/wallet:${TRAVIS_TAG} -f deploy/nginx/Dockerfile .

deploy:
- provider: script
  script: bash aws/deploy.sh $TRAVIS_TAG
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^prod|preprod$
