version: '3'
services:
    nginx:
        image: 866680356172.dkr.ecr.us-east-2.amazonaws.com/wallet:${tag}
        build:
            context: ..
            dockerfile: deploy/nginx/Dockerfile
            args:
                tag: ${tag}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
